# Generated by Django 4.2.7 on 2024-01-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_item_direction_alter_item_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='direction',
            field=models.FloatField(null=True, verbose_name='Направле'),
        ),
        migrations.AlterField(
            model_name='item',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='item',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='item',
            name='speed',
            field=models.FloatField(null=True, verbose_name='Скорость'),
        ),
    ]
